# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TC_COORDENADA',
            fields=[
                ('ID_COORDENADAN', models.AutoField(primary_key=True, serialize=False)),
                ('FILA_C', models.IntegerField()),
                ('COLUMNA_C', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TC_PATRON',
            fields=[
                ('ID_PARONT', models.AutoField(primary_key=True, serialize=False)),
                ('FILA_P', models.IntegerField(null=True)),
                ('COLUMNA_P', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tc_coordenada',
            name='ID_TC_PATRON',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas.TC_PATRON'),
        ),
    ]
