# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TC_COORDENADA',
            fields=[
                ('idcoordenada', models.AutoField(primary_key=True, serialize=False)),
                ('filac', models.IntegerField()),
                ('columnac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TC_PATRON',
            fields=[
                ('idpatron', models.AutoField(primary_key=True, serialize=False)),
                ('filap', models.IntegerField(null=True)),
                ('columnap', models.IntegerField(null=True)),
                ('contadorp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tc_coordenada',
            name='idtablapatron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.TC_PATRON'),
        ),
    ]
